version: 0.2
phases:
  install:
    commands:
      
  pre_build:
    commands:
    #run maven package command to prep jar files
      - mvn clean package
      - find . -mtime +10950 -exec touch {} \;
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket codepipeline-us-east-1-118146841898 --s3-prefix java-lambda-sample --output-template-file template-export.yml #"template-export.yml" name req'd by CodePipeline
artifacts:
  type: zip
  files:
    - template.yml
    - template-export.yml
    - pom.xml
    - lib/*
    - target/*
